services:
  app:
    build: .
    ports:
      - "3000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image:  postgres
    env_file:
      - .env
  redis:
    image: redis:8.0-rc1
    ports:
      - "6379:6379"
  